[theme]
primaryColor = "#32CD32"  # Lime Green
# Background color for the main content area
backgroundColor = "#000000"  # White
# Background color for sidebars and secondary elements
secondaryBackgroundColor = "#036478"  # Honeydew
textColor = "#FFFFFF"  # Dark Green
font = "sans serif"
